// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://treoiehmskdzqrdzrayw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyZW9pZWhtc2tkenFyZHpyYXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzE2MDcsImV4cCI6MjA2NDEwNzYwN30.Yu14-o9YnlHNEZzmhos50nxCJquVLZ-eOl8ptH7eOoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);